# [colors.bright]
# black = "#444b6a"
# blue = "#7da6ff"
# cyan = "#0db9d7"
# green = "#b9f27c"
# magenta = "#bb9af7"
# red = "#ff7a93"
# white = "#acb0d0"
# yellow = "#ff9e64"
#
# [colors.normal]
# black = "#32344a"
# blue = "#7aa2f7"
# cyan = "#449dab"
# green = "#9ece6a"
# magenta = "#ad8ee6"
# red = "#f7768e"
# white = "#787c99"
# yellow = "#e0af68"
#
# [colors.primary]
# background = "#1a1b26"
# foreground = "#a9b1d6"
#
# [colors.search.focused_match]
# background = "#ffb86c"
# foreground = "#44475a"
#
# [colors.search.matches]
# background = "#50fa7b"
# foreground = "#44475a"
#
# [colors.selection]
# background = "#44475a"
# text = "CellForeground"
#
# [colors.vi_mode_cursor]
# cursor = "CellForeground"
# text = "CellBackground"

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[font]
size = 11.0

[font.bold]
family = "JetBrains Mono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font Mono"
style = "Regular"

[window]
opacity = 1

[window.dimensions]
columns = 110
lines = 30

[window.padding]
x = 10
y = 10
