# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b6a38d01-887b-4f31-951b-b74379942f50";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-fdbe0b3a-6fcc-465c-9571-94e879089544".device = "/dev/disk/by-uuid/fdbe0b3a-6fcc-465c-9571-94e879089544";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4DFD-EE7E";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/bda8fee2-5067-49d7-b474-43ef3e285621";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-22e3957a-0317-4229-9390-508a3f448b72".device = "/dev/disk/by-uuid/22e3957a-0317-4229-9390-508a3f448b72";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
